import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar1 } from "../components/Navbars";
import {NextIntlClientProvider} from 'next-intl';
import { getLocale } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <NextIntlClientProvider>
          <Navbar1 />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
